# Site settings
title: Qualquer coisa
author: João Saragossa
email: joaosaragossa.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mesmo.
baseurl: "/jekyll-blog"
url: "http://joaosaragossa.github.io"
twitter_username: joaosaragossa
github_username:  joaosaragossa
permalink: /:title

# Build settings
markdown: kramdown