# Site settings
title: Blog com Jekyll
author: João Saragossa
email: joaosaragossa.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Esta é a descrição do blog. Jekyll é sensacional!
baseurl: "/jekyll-blog" # the subpath of your site, e.g. /blog/
url: "http://joaosaragossa.github.io" # the base hostname & protocol for your site
twitter_username: joaosaragossa
github_username:  joaosaragossa

# Build settings
markdown: kramdown